layout_spectrum: 0.7085106
typography_spectrum: 0
color:
  lightness: 0.0106383
  brandStrength: 0.6761287
  saturation: 1
  rhythmicContrast: 0
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Groover
